server:
  port: 8089
  servlet:
    context-path:
spring:
  profiles:
    active: @profiles.active@
  application:
    name: upload-demo
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

